### ISSUE TITLE
Deployment of Main branch code to new environment for QA and Release

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/k8-rebuild-file-drop#109]
Deployment of Main branch code to new environment for QA and Release

Ask in this task is to spin up a new deployment on AWS from the Main branch code, which can be used for release perspective of EAP team, we are picking up this exercise as currently there is only one environment https://labs.glasswallsolutions.com/ which has prod code available. In this new environment we do not need any domain name, ip address is fine for this.

**Comment by dtollaku** [comment]
FYI: @kumarsudhish we have renamed labs to cloud-sdk.glasswallsolutions.com. We will not use labs anymore.
