### ISSUE TITLE
XML report is truncated 

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild-file-drop#17]
XML report when downloaded seems to be truncated at least on the http://3.133.161.191/ deployment.  Every report just has [object Object] as its contents.

![image (9)](https://user-images.githubusercontent.com/70196799/102507522-a7341080-4084-11eb-8df8-919bbba73837.png)

**Comment by olegtaranenko** [comment]
I can't reproduce the issue in my local environment. If I set up a frontend application against a local docker image the XML report is generated without problem.

**Comment by GINAGC** [comment]
Hi, @olegtaranenko yes, this is in the implementation http://3.133.161.191/ -  there I can duplicate this issue all the time.

**Comment by GINAGC** [comment]
I am reopening this one, because this has to be validated once that the fix is deployed.

**Comment by MaNe2020** [comment]
@GINAGC when can we expect this fix to be deployed?

**Comment by GINAGC** [comment]
This is fixed.
