### ISSUE TITLE
New branch for SOW file drop and add to ci/cd

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild-file-drop#31]

**Comment by pranaysahith** [comment]
The SOW version of filedrop is created in below branches - 
sow_version branch in k8-rebuild-file-drop - https://github.com/k8-proxy/k8-rebuild-file-drop/tree/sow_version
sow_version branch in k8-rebuild - https://github.com/k8-proxy/k8-rebuild/tree/sow_version

centos_based branch in GW-Releases uses above branches - https://github.com/k8-proxy/GW-Releases/tree/centos_based
