### ISSUE TITLE
Fix File drop issue for customer - unable to access file drop UI

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/k8-rebuild-file-drop#33]
3 updates are needed on this next version for File drop:

1.- Take the latest from SOW team that is on main - https://github.com/filetrust/icap-infrastructure/tree/main/filedrop
2.- Fix k3s issue:

in the file drop OVA, once the IP address is configured, for some reason coredns and Nginx pod are not working because of some network issue (It is a known issue in k3s - https://github.com/k3s-io/k3s/issues/283)
It starts working fine once we restart the VM after the IP is configured.

3.- Update to use production SDK - https://github.com/filetrust/sdk-rebuild, so we use this version instead of the eval. - THIS IS ALREADY DONE FROM https://github.com/filetrust/icap-infrastructure/tree/main/filedrop

**Comment by MariuszFerdyn** [comment]
Solution:
`kubectl scale --replicas=0 deployment.apps/k8-rebuild-sow-rest
kubectl scale --replicas=0 ddeployment.apps/sow-rest-api
kubectl scale --replicas=0 deployment.apps/sow-rest-ui



kubectl scale --replicas=1 deployment.apps/k8-rebuild-sow-rest
kubectl scale --replicas=1 ddeployment.apps/sow-rest-api
kubectl scale --replicas=1 deployment.apps/sow-rest-ui


`

**Comment by naderaly** [comment]
Latest updates: Filedrop OVA and AMI created according latest from SOW team and using the production SDK
OVA link : s3://glasswall-sow-ova/vms/k8-rebuild-centos/k8-rebuild-centos-fadf51e7b9e729757345b78a7cda045da38bdf03-68.ova
AMI ID : ami-088fdad837dca6cf6
we already has two servers running on AWS and ESXI
https://34.246.198.221/ >> AWS
https://91.109.26.19/     >> ESXI
You can trigger "k8-rebuild" workflow from GW-Releases repository from branch "filedrop-centos" to build new AMI/OVA if we have any changes.
The networking issue still the easiest way to run "sudo systemctl restart  k3s docker" after configuring network as an installation step, but I will discuss with Nirvishek and Pranay to embed it in a script.
Repository structure :
GW-Releases (branch = filedrop-centos)
               |___ Vmware_script (branch = filedrop-centos)
               |___ K8-rebuild (branch = sow_version)
                                |___ k8-rebuild-file-drop (branch = sow_version)
                                |___ k8-rebuild-rest-api (branch = sow_version) (edited)

**Comment by naderaly** [comment]
@GINAGC moving this to Done column
