### ISSUE TITLE
Broken dependency with latest upgrades from Snyk

### ISSUE THREAD

**Issue by gurunathg** [k8-proxy/k8-rebuild-file-drop#35]
After upgradation of vulnerable packages from Snyk, build of docker image is failing. 

https://github.com/k8-proxy/k8-rebuild-file-drop/commit/324863c404a0af04ec6e86fc953c1e54bb0cf4ee
https://github.com/k8-proxy/k8-rebuild-file-drop/commit/bef11cac7596844608430ea8943a3c0f33b958dd

![image](https://user-images.githubusercontent.com/17300331/119086033-7e90b800-ba22-11eb-9485-27093d0a5159.png)

Aha! Link: https://glasswall-solutions.aha.io/epics/WAPP-E-18

**Comment by rajmbcoderx** [comment]
@GINAGC please let me know the branch to work on

**Comment by GINAGC** [comment]
@rajmbcoderx in main

**Comment by GINAGC** [comment]
@rajmbcoderx as agreed, please add the summary on the work done here.

**Comment by GINAGC** [comment]
@rajmbcoderx I need the details work done please.

**Comment by kumarsudhish** [comment]
Application URL : https://labs.glasswallsolutions.com/

**Comment by iamdeveloper-me** [comment]
Here are the points of analysis:

- I have upgraded the create-react-app version from 3.4.3 to 4.0.3. With that all other dependencies got crashed
- Then changed versions for following dependencies as well:
      react
      react-dom
      eslint
      eslint-plugin-import
- Right now I am able to run the code, with few bugs. Need to fix some Eslint issues and jsx properties.

Spent Hours: 4 hours almost
Will need: at least 10- 12 hours to make it work like before.

**Comment by iamdeveloper-me** [comment]
Update:  fixed few Es lint dependencies, and I am very close to fix the issue. I have tracked 10 hours, and will need around 3 or 4 more hours to make it work like before.

**Comment by iamdeveloper-me** [comment]
Update: fixed the issue with the latest version, 4.0.3. Application is up and running as before. Please find the attached the video link: https://www.loom.com/share/c63d5bba92a644c3bb063f06e179f508
Tracked Hours: 13h40m
