### ISSUE TITLE
Review Snyc detected vulnerabilities for k8-rebuild-file-drop

### ISSUE THREAD

**Issue by kekesimarti** [k8-proxy/k8-rebuild-file-drop#66]
1. Get access to Snyc
2. For the repository assigned, do an analysis of the vulnerabilities detected.
3. Confirm if any of the vulnerabilities can quickly solved.
4. Confirm from development perspective which vulnerabilities could have high impact in product.
5. Any additional information on the analysis.

**Comment by GINAGC** [comment]
duplicated with #35
